### ISSUE TITLE
Can't install with Astro 4.0

### ISSUE THREAD

**Issue by jannichorst** [sanity-io/sanity-astro#127]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Cannot install 'sanity-astro' with the astro 4.x. 

**To Reproduce**

1. `npm create astro@latest `
2. `npx astro add @sanity/astro @astrojs/react`
Or: `npm install @astrojs/react @sanity/astro @types/react-dom @types/react react-dom react`

**Expected behavior**

Successful installation of `sanity-astro`

**Log**
`
# npm resolution error report

While resolving: @0.0.1
Found: astro@4.0.8
node_modules/astro
  astro@"^4.0.8" from the root project

Could not resolve dependency:
peer astro@"^2.0.0 || ^3.0.0" from @sanity/astro@2.1.4
node_modules/@sanity/astro
  @sanity/astro@"^2.1.4" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
`

Tried the manual installation with the `--legacy-peer-deps`. this forces the installation

**Comment by mattobee** [comment]
Duplicate of https://github.com/sanity-io/sanity-astro/issues/122, which was fixed in https://github.com/sanity-io/sanity-astro/pull/124 but not yet published to NPM.

**Comment by LeanKhan** [comment]
Now published to NPM 🎉

**Comment by kmelve** [comment]
Should be solved in #149 – thanks for reporting! (Astro requires a default export for `npx astro add` installation)
