### ISSUE TITLE
Feature Request: `stega` client option

### ISSUE THREAD

**Issue by evankirkiles** [sanity-io/sanity-astro#130]
**Is your feature request related to a problem? Please describe.**

With the onset of Sanity's `Presentation` mode, it'd be wonderful if there were a way to enable stega-encoded CSMs from the backend with `@sanity/client/stega`. I understand that Astro doesn't exactly fit the `Presentation` mode rationale with its lack of live editing, but I'm quite interested in allowing users to have a more dedicated preview pane showing where content is coming from, even if it's not directly editable / only possible through a refresh. I've already set up a server-based draft mode that works well with the `sanity-plugin-iframe` component for viewing drafted content, and would love to take it into the `Presentation` pane to show document sources, but it seems as if there's no way in the current implementation to turn on stega mode.

**Describe the solution you'd like**

A configuration to use the stega client or even a separate export like `astro:sanity:stega` enabling including CSM's in the returned data.

**Comment by christianhg** [comment]
Hi! We've now updated the internal version of `@sanity/client`, so you should be able to configure Stega directly in the `sanity` config that this library exposes.

We also have a new `VisualEditing` component, tailored towards visual editing in Astro. Docs are still in the works in terms of how exactly to set up visual editing, but adding the component itself is fairly straightforward: https://github.com/sanity-io/sanity-astro?tab=readme-ov-file#enabling-visual-editing
