### ISSUE TITLE
__vite_ssr_import_3__.default is not a function

### ISSUE THREAD

**Issue by PaulieScanlon** [sanity-io/sanity-astro#148]
**Describe the bug**
I think the npx script add the wrong import to `astro.config.mjs`

**To Reproduce**

Install the integration using: 
```
npx astro add @sanity/astro @astrojs/react
```

which adds the following to`astro.config.mjs`
```
import sanity from '@sanity/astro';
```

I think the correct import should be:

```
import { sanityIntegration } from '@sanity/astro';
```

**Comment by kmelve** [comment]
Should be solved in #149 – thanks for reporting! (Astro requires a default export for `npx astro add` installation)
