### ISSUE TITLE
Admin page goes to 404 not found

### ISSUE THREAD

**Issue by Wooody82** [sanity-io/sanity-astro#155]
I use sanity with astro latest versions. When we visit admin page as I use route path the admin page works but if we visit anything there and refresh the page it goes to 404. plus if we save any post now it save the post but it show blank white and error!

**To Reproduce**

1. Go to admin page
2. Click on click on anything
3. Refresh the page
4. See error 404 not found
5. if we save post we get this error in dev log
Uncaught Error: Sanity LocaleContext value missing. Is this hook being used outside LocaleContext.Provider?
    at useLocale (useLocale.ts:22:11)
    at useCurrentLocale (useLocale.ts:12:10)
    at useListFormat (useListFormat.ts:37:25)
    at Translate (Translate.tsx:112:22)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    

**Expected behavior**
The Admin page should work even if we refresh it.

**Which versions of Sanity are you using?**
@sanity/cli (global)                   3.36.1 (up to date)
@sanity/asset-utils                     1.3.0 (up to date)
@sanity/astro                           3.0.0 (up to date)
@sanity/document-internationalization   2.1.0 (up to date)
@sanity/google-maps-input               3.0.2 (up to date)
@sanity/image-url                       1.0.2 (up to date)
@sanity/types                          3.36.1 (up to date)
@sanity/vision                         3.36.1 (up to date)
sanity                                 3.36.1 (up to date)

**What operating system are you using?**
macOs 14.4 Beta (23E5180j)

**Which versions of Node.js / npm are you running?**
v18.18.2

**Comment by 3200pro** [comment]
> The issue from @sanity/astro 3.0.0 .. I downgrade it to 2.2.1
> 
> And I need to change the import in config like this: import {sanityIntegration as sanity} from "@sanity/astro";
> 
> instead of import sanity from "@sanity/astro";

That worked here. LMK When 3.0.0 is GTG:)

**Comment by dewodt** [comment]
> The issue from @sanity/astro 3.0.0 .. I downgrade it to 2.2.1
> 
> And I need to change the import in config like this: import {sanityIntegration as sanity} from "@sanity/astro";
> 
> instead of import sanity from "@sanity/astro";

Worked for me! Thank you

**Comment by christianhg** [comment]
Thank you for reporting this. The latest version, `3.0.1`, should fix this issue.

**Comment by 3200pro** [comment]
> Thank you for reporting this. The latest version, `3.0.1`, should fix this issue.

Welcome to the Sanity team! Congrats on the new position:)
