### ISSUE TITLE
New Presentation/Visual Editing tool not working on clean and existing Astro project

### ISSUE THREAD

**Issue by DennisKraaijeveld** [sanity-io/sanity-astro#175]
**Describe the bug**

```
renderVisualEditing.js?v=e31608a7:1 Uncaught (in promise) SyntaxError: The requested module '/node_modules/react-is/index.js?v=e31608a7' does not provide an export named 'isValidElementType' (at renderVisualEditing.js?v=e31608a7:1:2047)
```

**To Reproduce**

Follow the Sanity/Astro tutorial to create a clean Astro-Sanity project. 

I am trying to setup visual editing but inside my existing project as a new clean Astro project I do get errors and there is no way to connect. My sanity config:

```
...,
plugins: [
		structureTool(),
		presentationTool({
			previewUrl: 'http://localhost:4321/',
		}),
],
...,

```
```
---
import { VisualEditing } from '@sanity/astro/visual-editing'
---

<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
		<meta name="viewport" content="width=device-width" />
		<meta name="generator" content={Astro.generator} />
		<title>Astro</title>
	</head>
	<body>
		<h1>Astro</h1>
		<VisualEditing enabled={true} zIndex={1000} />
	</body>
</html>
```

**Screenshots**
<img width="1390" alt="Screenshot 2024-05-24 at 11 36 43" src="https://github.com/sanity-io/sanity-astro/assets/50783193/f5ba8463-aa7e-4704-842d-e7707eaa5bfb">

**Which versions of Sanity are you using?**

@sanity/cli (global)  3.30.1 (latest: 3.43.0)
@sanity/astro          3.1.0 (up to date)
@sanity/types         3.43.0 (up to date)
sanity                3.43.0 (up to date)

**What operating system are you using?**

Mac OS

**Which versions of Node.js / npm are you running?**

10.5.0
v20.11.0

**Comment by christianhg** [comment]
Thank you for reporting this. I'll look into it.

**Comment by christianhg** [comment]
Hi again! 

Could you try the latest version, `v3.1.3`, and see if it works? It should! 🤞 

Please note that your Astro app will need the [React integration](https://docs.astro.build/en/guides/integrations-guide/react/) for visual editing to work (it's a React component).

More docs will come soon, but hopefully this latest release make the overlay work for you.

**Comment by DennisKraaijeveld** [comment]
@christianhg Yes, working now! Thanks. It's a bit unstable in terms of finding import resolutions and type declarations depending on how you setup your tsconfig, but ignoring the errors for now. Everything is working great

**Comment by DennisKraaijeveld** [comment]
Well actually, building the project does break. But I am using Turborepo so it might because of that

```
12:42:02 [ERROR] [vite] x Build failed in 465ms
Rollup failed to resolve import "@sanity/visual-editing/react" from "/Users/dennis/Developer/xxllnc-turborepo/node_modules/@sanity/astro/dist/visual-editing/visual-editing-component.tsx".
```

**Comment by christianhg** [comment]
Thanks for the feedback! Do you have `@sanity/visual-editing` in your `dependencies`? It's a peer dependency of `@sanity/astro` now.

**Comment by Jay-Ferguson** [comment]
I am running into a similar issue, seems that the connection for the preview fails I am running sanity 3.4.4 and the latest version of astro. It seems that the websocket is just not able to connect, not sure where the error is but the error 
- "WebSocket connection to 'wss://9gy3ebd9.api.sanity.io/v2022-06-30/socket/production?tag=sanity.studio' failed: WebSocket is closed before the connection is established."

**Comment by DennisKraaijeveld** [comment]
> Thanks for the feedback! Do you have `@sanity/visual-editing` in your `dependencies`? It's a peer dependency of `@sanity/astro` now.

That was exactly the thing. Thanks. Everything is working perfectly.

**Comment by christianhg** [comment]
Great to hear! I'll close this issue now.

@Jay-Ferguson , could you open a new issue for the problem you are facing, perhaps representing a repository to reproduce or some reproduction steps?

**Comment by Jay-Ferguson** [comment]
> @sanity/visual-editing

I can create a new issue, but before I do that I should confirm that visual editing is only possible with the actual data that the editor will be updating via the visual editor is created from a react component? As many of the pages on the site that I would like to edit are just astro files I don't want to try this solution if I don't even know if it is possible.

**Comment by DennisKraaijeveld** [comment]
It does work on .Astro files.

**Comment by Jay-Ferguson** [comment]
> sanityClient

I am looking at the example in the sanity docs - https://www.sanity.io/docs/loaders 

but it states under what about SSG it - "While static site generators can make it simple to build websites, they are not well-suited for providing a Visual Editing experience for content teams. Static site generators pre-render pages at build time, meaning any content changes require a full or partial site rebuild. This usually doesn't scale well as the site grows and does not provide the real-time editing experience that Loaders enable.

However, some frameworks, like Astro, also support server-side rendering. Suppose you wish to use static site generation for your production builds. In that case, a strategy can be to set up a secondary deployment for previews that uses server-side rendering with Loaders." So I would assume this means I would only be able to set this up using SSR on each route that would need visual editing enabled?

**Comment by DennisKraaijeveld** [comment]
Yes, but in my case I don't feel the speed difference comparing SSG and SSR, if you setup proper caching and validation.

However, the example sets the Visual Editing on and off using a ENV variable, so you might do that as well and provide a second deployment for your client which will be the preview/staging with SSR enabled. And whenever they deploy the updated content, you trigger a new build for your production.

It should be able to enable draft mode using an API route within your application, but I have not tried that yet with the latest update.

**Comment by Jay-Ferguson** [comment]
Ok I see, for my clients case SSG would be optimal to reduce hosting costs, I assume this makes it basically impossible to set up visual editing without either SSR or CSR for real time. Just to clarify to get around this limitation I would set up another staging environment on Netlify based off an another git branch, change that to be rendered on the server and use the loader data with draft mode in the API routes? I appreciate the help, would you be able to link the example, as I just want to make sure we are referring to the same code.
